services:
  ailian-manus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feifei-mcpo
    ports:
      - "8888:8888"
    restart: unless-stopped
    networks:
      - ailian-network
networks:
  ailian-network:
    driver: bridge