[project]
name = "ailian-manus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dynaconf>=3.2.11",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
]
